# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('titulo', models.CharField(max_length=50, verbose_name='T\xedtulo de eleitor')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('email', models.CharField(max_length=34, verbose_name='E-mail')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('endereco', models.CharField(max_length=128, verbose_name='Endere\xe7o')),
                ('bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('mora_com_pais', models.BooleanField(verbose_name='Mora com os pais?')),
                ('telefone_fixo', models.CharField(max_length=13, verbose_name='Telefone fixo')),
                ('telefone_movel', models.CharField(max_length=13, verbose_name='Telefone celular')),
                ('registro_academico', models.CharField(max_length=20, verbose_name='Registro Acad\xeamico')),
                ('tem_whatsapp', models.BooleanField(verbose_name='Tem Whatsapp?')),
                ('inst_ensino_nome', models.CharField(max_length=30, verbose_name='Institui\xe7\xe3o de ensino')),
                ('inst_ensino_cicade', models.CharField(max_length=10, verbose_name='Cidade da institui\xe7\xe3o')),
                ('curso', models.CharField(max_length=25, verbose_name='Curso')),
                ('duracao_curso', models.IntegerField(verbose_name='Dura\xe7\xe3o do curso (Anos)')),
                ('semestre_matriculado', models.BooleanField(verbose_name='Semestre atual matriculado')),
                ('turno', models.CharField(choices=[('M', 'Manh\xe3'), ('T', 'Tarde'), ('N', 'Noite'), ('MT', 'Manh\xe3 / Tarde'), ('MTN', 'Manh\xe3 / Tarde / Noite'), ('TN', 'Tarde / Noite'), ('MN', 'Manh\xe3 / Noite')], max_length=2, verbose_name='Turno')),
                ('servicos', models.CharField(choices=[('FIES', 'FIES'), ('PROUNI', 'PROUNI'), ('PEP', 'PEP'), ('OUTROS', 'OUTRO (COLOCAR NA OBSERVA\xc7\xc3O)'), ('NENHUM', 'NENHUM')], default='NENHUM', max_length=7, verbose_name='Servi\xe7os')),
                ('situacao', models.CharField(choices=[('N', 'Novo'), ('R', 'Renova\xe7\xe3o')], max_length=2, verbose_name='Situa\xe7\xe3o')),
                ('dias_utilizacao', models.CharField(choices=[('SEGUNDA', 'SEGUNDA-FEIRA'), ('TER\xc7A', 'TER\xc7A-FEIRA'), ('QUARTA', 'QUARTA-FEIRA'), ('QUINTA', 'QUINTA-FEIRA'), ('SEXTA', 'SEXTA-FEIRA'), ('S\xc1BADO', 'S\xc1BADO')], default='SEGUNDA', max_length=8, verbose_name='Dias de utiliza\xe7\xe3o')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est\xe1 ativo?')),
                ('foto', models.CharField(blank=True, max_length=128, verbose_name='Foto')),
            ],
            options={
                'ordering': ('nome', 'cpf', 'is_active'),
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
