# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_auto_20170817_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chamados',
            new_name='Chamado',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=15, verbose_name='CPF'),
        ),
    ]
