# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_auto_20170817_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(default='', max_length=100, verbose_name='T\xedtulo'),
        ),
    ]
