# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_chamado_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.FileField(upload_to=b''),
        ),
    ]
