# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_auto_20170817_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
