# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 22:47
from __future__ import unicode_literals

import alunos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_auto_20170818_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovante_residencia1', models.FileField(blank=True, null=True, upload_to=alunos.models.user_directory_path)),
                ('comprovante_residencia2', models.FileField(blank=True, null=True, upload_to=alunos.models.user_directory_path)),
                ('comprovante_residencia3', models.FileField(blank=True, null=True, upload_to=alunos.models.user_directory_path)),
                ('cpf', models.FileField(blank=True, null=True, upload_to=alunos.models.user_directory_path)),
                ('titulo_eleitor', models.FileField(blank=True, null=True, upload_to=alunos.models.user_directory_path)),
                ('foto', models.FileField(blank=True, null=True, upload_to=alunos.models.user_directory_path)),
                ('declaracao', models.FileField(blank=True, null=True, upload_to=alunos.models.user_directory_path)),
                ('grade', models.FileField(blank=True, null=True, upload_to=alunos.models.user_directory_path)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Aluno')),
            ],
        ),
    ]
