# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 13:54
from __future__ import unicode_literals

import alunos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_documentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=alunos.models.user_directory_path)),
                ('is_valid', models.BooleanField(default=False)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentacao',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Est\xe1 ativo?'),
        ),
        migrations.DeleteModel(
            name='Documentacao',
        ),
        migrations.AddField(
            model_name='documentocpf',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Aluno'),
        ),
    ]
