# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 18:46
from __future__ import unicode_literals

import alunos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_auto_20170819_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=alunos.models.user_directory_path)),
                ('is_valid', models.BooleanField(default=False)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Aluno')),
            ],
            options={
                'verbose_name': 'Documenta\xe7\xe3o RG',
                'verbose_name_plural': 'Documentos - RG',
            },
        ),
        migrations.AlterModelOptions(
            name='documentocpf',
            options={'verbose_name': 'Documenta\xe7\xe3o CPF', 'verbose_name_plural': 'Documentos - CPF'},
        ),
    ]
