# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_auto_20170819_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, verbose_name='Cidade')),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='inst_ensino_cicade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Cidade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est\xe1 ativo?'),
        ),
    ]
